##
##  SpeechFlow - Speech Processing Flow Graph
##  Copyright (c) 2024-2026 Dr. Ralf S. Engelschall <rse@engelschall.com>
##  Licensed under GPL 3.0 <https://spdx.org/licenses/GPL-3.0-only>
##

#   [top-level] (internal): just pass-through "npm install" operation
post-install
    execa -c speechflow-cli   npm install && \
    execa -c speechflow-ui-db npm install && \
    execa -c speechflow-ui-st npm install

#   [top-level] automatically update all NPM dependencies
upd
    npx -y upd && \
    execa -c speechflow-cli   npx -y upd && \
    execa -c speechflow-ui-db npx -y upd && \
    execa -c speechflow-ui-st npx -y upd

#   [top-level] provide statistics about code base
cloc
    cloc etc \
        speechflow-cli/etc   speechflow-cli/src   \
        speechflow-ui-db/etc speechflow-ui-db/src \
        speechflow-ui-st/etc speechflow-ui-st/src

#   [top-level] lint components for development
lint
    execa -c speechflow-cli   npm start lint && \
    execa -c speechflow-ui-db npm start lint && \
    execa -c speechflow-ui-st npm start lint
    secretlint --secretlintrc etc/secretlint.json speechflow-*/src/**/*

#   [top-level] build components for production (full build)
build : lint
    execa -c speechflow-cli   npm start build && \
    execa -c speechflow-ui-db npm start build && \
    execa -c speechflow-ui-st npm start build

#   [top-level] (internal) build components for development (partial build only)
build:dev : lint
    execa -c speechflow-cli   npm start build && \
    execa -c speechflow-ui-db npm start build && \
    execa -c speechflow-ui-st npm start build

#   [top-level] (internal) build components for development (continuous file watching)
build:dev:watch
    watch "npm start build:dev" \
        speechflow-cli/src \
        speechflow-ui-db/src \
        speechflow-ui-st/src \
        --wait=2 --interval=1

#   [top-level] (internal) run command-line interface for production
run:dev:watch
    wait-on -l "speechflow-cli/dst/speechflow.js" && \
    cross-env NODE_OPTIONS="--no-warnings" \
        nodemon --signal SIGINT -w speechflow-cli/dst --delay 1500ms \
            speechflow-cli/dst/speechflow.js -- \
            $SPEECHFLOW_OPTIONS

#   [top-level] (internal) run command-line interface for development (continuous file watching)
run:dev
    concurrently -p "[{name}]" -n "build,run" -c "blue,red" \
        "npm start build:dev:watch" \
        "npm start run:dev:watch"

#   [top-level] test drive
test
    node --enable-source-maps speechflow-cli/dst/speechflow.js \
        -v info -c studio-translation@etc/speechflow.yaml \
        -d audio:audio-de:DE,text:text-de-interim:DE-Interim,text:text-en-interim:EN-Interim,text:text-de-final:DE-Final,text:text-en-final:EN-Final,audio:audio-en:EN

#   [top-level] remove all generated artifacts (reverse of "npm start build")
clean
    execa -c speechflow-cli   npm start clean && \
    execa -c speechflow-ui-db npm start clean && \
    execa -c speechflow-ui-st npm start clean

#   [top-level] remove all generated artifacts (reverse of "npm install" and "npm start build")
clean:dist
    execa -c speechflow-cli   npm start clean:dist && \
    execa -c speechflow-ui-db npm start clean:dist && \
    execa -c speechflow-ui-st npm start clean:dist && \
    shx rm -f package-lock.json && \
    shx rm -rf node_modules

#   run Claude Code
claude
    npx -y dumpall -e node_modules -e .git -e .env -e dst . >etc/claude.dump.md
    claude "/suck @etc/claude.dump.md"

